DEFAULT_WIDTH = 800
DEFAULT_HEIGHT = 600
DEFAULT_LOOKAT_X = 0.0
DEFAULT_LOOKAT_Y = 0.0
DEFAULT_LOOKAT_Z = 0.0

# Camera spherical coordinates defaults
DEFAULT_CAMERA_DISTANCE = 5.0
DEFAULT_CAMERA_AZIMUTH = -90.0  # degrees
DEFAULT_CAMERA_ELEVATION = 30.0  # degrees

TARGET_FPS = 30.0
UI_REFRESH_INTERVAL_MS = 16
THREAD_JOIN_TIMEOUT = 1.0