Optimization:
  GENERATION: 500
  POPULATION: 100  # int(4 + 3 * math.log(211))
  MU: 10
  SIGMA: 0.3

  Evaluation:
    FOOD_RANGE: 2.236067977
    FOOD_NEST_GAIN: 1
    FOOD_ROBOT_GAIN: 0.001

Task:
  EPISODE: 60

  Nest:
    POSITION: [ 0, 0 ]
    SIZE: 0.5

  Robot:
    POSITIONS: [
      [ -0.45,  0.45, 90 ], [ 0,  0.45, 90 ], [ 0.45,  0.45, 90 ],
      [ -0.45,  0.00, 90 ], [ 0,  0.00, 90 ], [ 0.45,  0.00, 90 ],
      [ -0.45, -0.45, 90 ], [ 0, -0.45, 90 ], [ 0.45, -0.45, 90 ],
    ]

  Food:
    POSITIONS: [
      [ 0, -6 ], [ 0, 6 ]
    ]

Simulation:
  TIMESTEP: 0.01

Renderer:
  MAX_GEOM: 7800
  RESOLUTION: [ 900, 1350 ]

Structure:
  Environment:
    CELL_SIZE: 0.2
    WIDTH: 80
    HEIGHT: 90

  Robot:
    THINKING_INTERVAL: 0.3
    MAX_SECRETION: 2.569317817
    MOVE_SPEED: 1.2
    TURN_SPEED: 1.0

    SENSOR_PRECISION: [ 2 / 0.7, 2 / 5 ]
