Display:
  MAX_GEOM: 7800
  RESOLUTION: [ 500, 500 ]
  ZOOM: 13

Plot:
  START: 0
  END: 5

Simulation:
  EPISODE_LENGTH: 60
  TIMESTEP: "eval: 0.033333 / 5"

Pheromone:
  NUM_CELL: [ 51, 51 ]
  CENTER_INDEX: [
    "eval: int($Pheromone.NUM_CELL[0] * 0.5)",
    "eval: int($Pheromone.NUM_CELL[1] * 0.5)"
  ]

  CELL_SIZE_FOR_CALCULATION: 1
  CELL_SIZE_FOR_MUJOCO: 0.2

  MIN_SV: 0.001
  LIQUID: 1000000000

Optimization:
  GENERATION: 50
  POPULATION: 50
  NUM_ELITE: "eval: int($Optimization.POPULATION * 0.5)"
  SIGMA: 0.3

  Range:
    SATURATION_VAPOR: 100
    EVAPORATION: 100
    DIFFUSION: 100
    DECREASE: 100

  Target:
    RELATIVE_STABLE_GAS_VOLUME: 0.6
    INCREASE_TIME: 5
    DECREASE_TIME: 5
    FIELD_SIZE: 0.350

  Weight:
    WEIGHT: "eval: [ 0, 0, 1 ]" # sv_err, dec_volume_err, size_err,
    CONSISTENCY_WEIGHT: 0 # 1
    L2: 0.0